import { useEffect, useState } from 'react';
import { Download, FileText, Loader2, CheckCircle2, FolderOpen } from 'lucide-react';
import { COMPANIES, type Content, type Locale, type ApiResult } from '../shared/model';
import { defaultDocumentOptions, documentBody, documentCss, type DocumentOptions } from '../shared/document';
import { Field } from './Studio';

async function unwrap<T>(result: Promise<ApiResult<T>>): Promise<T> { const response = await result; if (!response.ok) throw new Error(response.error); return response.value; }
export function DocumentPage({ content, locale, imageUrl, onError }: { content: Content; locale: Locale; imageUrl: string; onError: (message: string) => void }) {
  const [options, setOptions] = useState<DocumentOptions>(() => defaultDocumentOptions(content, locale));
  const [ready, setReady] = useState(false);
  const [busy, setBusy] = useState(false);
  const [output, setOutput] = useState('');
  useEffect(() => { let active = true; void unwrap(window.studio.documentSettings(locale)).then(saved => { if (active && saved) setOptions(saved); }).catch(error => onError(error.message)).finally(() => { if (active) setReady(true); }); return () => { active = false; }; }, []);
  useEffect(() => { if (ready) void unwrap(window.studio.saveDocumentSettings(options)).catch(error => onError(error.message)); }, [options, ready]);
  useEffect(() => { setOptions(previous => ({ ...previous, locale })); }, [locale]);
  const change = <K extends keyof DocumentOptions>(key: K, value: DocumentOptions[K]) => setOptions(previous => ({ ...previous, [key]: value }));
  const chooseKind = (kind: DocumentOptions['kind']) => setOptions(previous => ({ ...previous, kind, title: kind === 'resume' ? (locale === 'ko' ? '이력서' : 'Resume') : (locale === 'ko' ? '경력기술서' : 'Career Portfolio') }));
  const exportPdf = async () => { setBusy(true); onError(''); try { const result = await unwrap(window.studio.exportDocument(content, options)); if (result) setOutput(result); } catch (error) { onError(error instanceof Error ? error.message : 'PDF를 만들지 못했어요.'); } finally { setBusy(false); } };
  const selected = content.languages[locale];
  const imageData = imageUrl || undefined;
  return <div className="document-layout"><section className="document-controls"><div className="panel"><div className="panel-title"><h2>어떤 문서를 만들까요?</h2></div><div className="document-kind"><button className={options.kind === 'resume' ? 'active' : ''} onClick={() => chooseKind('resume')}><FileText size={20} /><strong>이력서</strong><small>핵심 경험을 간결하게</small></button><button className={options.kind === 'career' ? 'active' : ''} onClick={() => chooseKind('career')}><FileText size={20} /><strong>경력기술서</strong><small>회사별 업무와 성과를 자세히</small></button></div><div className="field-grid"><Field label="문서 제목" value={options.title} onChange={value => change('title', value)} wide /><Field label="이름" value={options.name} onChange={value => change('name', value)} /><Field label="직무 / 경력" value={options.role} onChange={value => change('role', value)} /><Field label="이메일" value={options.email} onChange={value => change('email', value)} /><Field label="전화번호 (선택)" value={options.phone} onChange={value => change('phone', value)} /><Field label="거주 지역 (선택)" value={options.location} onChange={value => change('location', value)} wide /></div><p className="field-note">문서용 인적사항은 이 PC에 보관돼요.</p></div>
    <div className="panel"><label className="field"><span>소개 / 핵심 역량</span><textarea rows={5} value={options.summary} onChange={event => change('summary', event.target.value)} /></label><button className="text-button" onClick={() => change('summary', defaultDocumentOptions(content, locale).summary)}>현재 소개글에서 다시 가져오기</button><label className="field"><span>학력 / 자격 (선택)</span><textarea rows={3} value={options.education} onChange={event => change('education', event.target.value)} placeholder="학교 / 전공 / 기간 또는 보유 자격을 입력해 주세요." /></label></div>
    <div className="panel"><div className="panel-title"><h2>포함할 경험</h2><span>필요한 항목만 선택하세요</span></div><div className="check-list">{COMPANIES.map(company => <label key={company}><input type="checkbox" checked={options.companies.includes(company)} onChange={event => change('companies', event.target.checked ? [...options.companies, company] : options.companies.filter(id => id !== company))} /><span>{selected.companies[company].title}<small>{selected.companies[company].period}</small></span></label>)}</div><h3 className="small-heading">프로젝트</h3><div className="check-list">{selected.projects.map(project => <label key={project.id}><input type="checkbox" checked={options.projects.includes(project.id)} onChange={event => change('projects', event.target.checked ? [...options.projects, project.id] : options.projects.filter(id => id !== project.id))} /><span>{project.title}</span></label>)}</div></div>
    <div className="panel"><div className="panel-title"><h2>문서 스타일</h2></div><div className="accent-picker">{(['navy', 'forest', 'charcoal'] as const).map(accent => <button key={accent} aria-label={accent} className={`${accent} ${options.accent === accent ? 'active' : ''}`} onClick={() => change('accent', accent)} />)}</div><label className="checkbox-line"><input type="checkbox" checked={options.includePhoto} onChange={event => change('includePhoto', event.target.checked)} /> 프로필 사진 포함</label><p className="field-note">A4 · 선택 가능한 텍스트 · 페이지 번호 포함</p><button className="primary export-button" disabled={busy || !ready || !options.name.trim()} onClick={() => void exportPdf()}>{busy ? <Loader2 size={17} className="spin" /> : <Download size={17} />}{busy ? '문서를 만드는 중' : 'PDF로 저장'}</button>{output && <div className="pdf-saved"><CheckCircle2 size={16} /> PDF를 저장했어요.<button className="text-button" onClick={() => void unwrap(window.studio.revealDocument()).catch(error => onError(error.message))}><FolderOpen size={15} /> 폴더 열기</button></div>}</div>
  </section><aside className="document-preview"><div className="preview-heading"><span className="status-dot" /> 문서 미리보기 <span>A4</span></div><div className="paper-wrap"><style>{documentCss}</style><div className="paper" dangerouslySetInnerHTML={{ __html: documentBody(content, options, imageData) }} /></div><p className="preview-footnote">본문은 선택한 콘텐츠로 재구성돼요.<br />페이지 나눔과 번호는 PDF 저장 시 적용돼요.</p></aside></div>;
}
